/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#131315",
        "inverse-primary": "#bd0d1d",
        "tertiary": "#ffb0ca",
        "on-tertiary-container": "#ffd0dd",
        "on-tertiary-fixed": "#3e001f",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "on-surface-variant": "#e5bdb9",
        "tertiary-container": "#bd006a",
        "surface-tint": "#ffb3ad",
        "on-secondary-fixed": "#241a00",
        "outline-variant": "#5c403d",
        "on-primary-fixed-variant": "#930011",
        "on-tertiary-fixed-variant": "#8d004e",
        "tertiary-fixed-dim": "#ffb0ca",
        "error": "#ffb4ab",
        "surface-container": "#201f21",
        "surface-container-high": "#2a2a2c",
        "error-container": "#93000a",
        "surface-container-highest": "#353437",
        "secondary-container": "#af8d11",
        "inverse-surface": "#e5e1e4",
        "on-secondary-container": "#342800",
        "on-tertiary": "#640035",
        "on-surface": "#e5e1e4",
        "primary-fixed": "#ffdad6",
        "secondary": "#e9c349",
        "surface-container-low": "#1c1b1d",
        "surface-bright": "#39393b",
        "primary-fixed-dim": "#ffb3ad",
        "on-primary": "#680009",
        "surface-variant": "#353437",
        "on-background": "#e5e1e4",
        "on-primary-container": "#ffd2ce",
        "outline": "#ac8885",
        "on-primary-fixed": "#410003",
        "surface-dim": "#131315",
        "surface-container-lowest": "#0e0e10",
        "background": "#131315",
        "inverse-on-surface": "#313032",
        "on-secondary": "#3c2f00",
        "primary-container": "#c1121f",
        "tertiary-fixed": "#ffd9e3",
        "on-secondary-fixed-variant": "#574500",
        "primary": "#ffb3ad",
        "secondary-fixed": "#ffe088",
        "secondary-fixed-dim": "#e9c349"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Manrope"],
        "label": ["Space Grotesk"]
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
    },
  },
  plugins: [],
}